from building import *

cwd = GetCurrentDir()

src = []
# highfreq_thread.c is intentionally excluded: it depends on unfinished
# sensor/HIL/control interfaces. The DPS368 driver is also excluded while
# this stage only tests RT-Thread scheduling and IPC.
src += ['app/main.c', 'app/flight_shell.c', 'app/mp_ipc.c']
src += Glob('app/*.cpp')
src += Glob('port/*.c')
src += Glob('task_thread/*.c')
src += Glob('core/math/*.c')
src += Glob('core/filter/*.c')
src += Glob('core/attitude/*.c')
src += Glob('core/control/*.c')
src += Glob('core/mixer/*.c')
src += Glob('middleware/topic/*.c')

CPPPATH = [cwd + '/include',
           cwd + '/task_thread']

group = DefineGroup('myPilot_lite', src,
                    depend=['BSP_USING_MYPILOT_LITE'],
                    CPPPATH=CPPPATH)

Return('group')
