import os
from building import *

cwd = GetCurrentDir()
objs = []

for entry in os.listdir(cwd):
    sconscript = os.path.join(cwd, entry, 'SConscript')
    if os.path.isfile(sconscript):
        objs += SConscript(sconscript)

Return('objs')
